### ISSUE TITLE
Ultianalytics API

### ISSUE THREAD

**Issue by kevinmcc21** [kyletns/classy-highlights#2]
Where did you find information on the ultianalytics API?  I am having trouble finding that information on their site.

**Comment by kyleschmolze** [comment]
It's not publicly documented, but I emailed them and they sent me back some documentation. Basically, you just consume the same API their website consumes. So open your dev console and watch the network requests go back and forth, and you can recreate those from your own server. Here is the documentation I did get from there, although for most of my use case I just used the dev console to poke around :) Good luck! Are you building something?

[authenticate.txt](https://github.com/kyleschmolze/plastic-disco/files/2828091/authenticate.txt)
[UltiAnalyticsAPI.zip](https://github.com/kyleschmolze/plastic-disco/files/2828092/UltiAnalyticsAPI.zip)

**Comment by kevinmcc21** [comment]
Thanks for sharing!  I am starting to build something, though it's mostly just concept at this point.

So to clarify one point: All of these queries are for specific team_ids, correct?  I am looking around for something that will download the list of team_id's (because otherwise I will have to crawl through and identify the team_ids manually).  My goal is to basically download their entire database, or as much of it as I can fit onto my VM.

Thanks again!
Kevin

On Mon, Feb 4, 2019 at 8:11 AM Kyle Schmolze <notifications@github.com<mailto:notifications@github.com>> wrote:

It's not publicly documented, but I emailed them and they sent me back some documentation. Basically, you just consume the same API their website consumes. So open your dev console and watch the network requests go back and forth, and you can recreate those from your own server. Here is the documentation I did get from there, although for most of my use case I just used the dev console to poke around :) Good luck! Are you building something?

authenticate.txt<https://github.com/kyleschmolze/plastic-disco/files/2828091/authenticate.txt>
UltiAnalyticsAPI.zip<https://github.com/kyleschmolze/plastic-disco/files/2828092/UltiAnalyticsAPI.zip>

**Comment by kyleschmolze** [comment]
Ha well it wouldn't surprise me if they didn't build an endpoint that made it easy to download their entire database haha, but you should definitely reach out to them directly at support@ultianalytics.com

**Comment by kevinmcc21** [comment]
Yeah I mean I guess I can understand that, although teams still have the option to password protect their data, so I'd only be downloading the "public" data anyway.

I did email them prior to emailing you but haven't heard back yet.  Not holding my breath at this point. :)

On Sun, Feb 10, 2019 at 4:50 PM Kyle Schmolze <notifications@github.com<mailto:notifications@github.com>> wrote:

Ha well it wouldn't surprise me if they didn't build an endpoint that made it easy to download their entire database haha, but you should definitely reach out to them directly at support@ultianalytics.com<mailto:support@ultianalytics.com>

**Comment by elastufka** [comment]
Any luck on getting that team ID list? I'm also interested in downloading a lot of data...

**Comment by kevinmcc21** [comment]
I abandoned this project soon after I started but the attached files seem to be the closest thing to a team ID list I was able to find.  (I can't even find the code that pulled it, ha.)

On Tue, Oct 13, 2020 at 2:59 AM elastufka <notifications@github.com<mailto:notifications@github.com>> wrote:

Any luck on getting that team ID list? I'm also interested in downloading a lot of data...
